<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>FeeEditor.Cli</AssemblyName>
    <RootNamespace>FeeEditor.Cli</RootNamespace>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../core/Core.csproj" />
  </ItemGroup>
</Project>
