<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FeeEditor.Core</AssemblyName>
    <RootNamespace>FeeEditor.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data/items.json" LogicalName="FeeEditor.Core.Data.items.json" />
  </ItemGroup>
</Project>
